gns3_server_url: "http://10.255.255.11:3080"

project_name: "NX-OS_mgmt_network"

nodes:
  switch-1:
    template_name: "Ethernet switch"
    x: 0
    y: 0

  csr1000v-1:
    template_name: "Cisco CSR1000v 16.7.1"
    cmdfile: "csr1kv"
    x: 0
    y: -170
    ip: "192.168.1.13 255.255.255.0"
    gw: "192.168.1.1"

  cisconx-1:
    template_name: "Cisco NX-OSv 9000 9300v 10.1.1"
    cmdfile: "nxos"
    x: -200
    y: 0
    ip: "192.168.1.11/24"
    gw: "192.168.1.1"

  cisconx-2:
    template_name: "Cisco NX-OSv 9000 9500v 10.1.1"
    cmdfile: "nxos"
    x: 200
    y: 0
    ip: "192.168.1.12/24"
    gw: "192.168.1.1"

links:
  -
    - name: "switch-1"
      interface: 1
    - name: "cisconx-1"
      interface: 0
  -
    - name: "switch-1"
      interface: 2
    - name: "cisconx-2"
      interface: 0
  -
    - name: "switch-1"
      interface: 3
    - name: "csr1000v-1"
      interface: 0
